### ISSUE TITLE
[FEATURE] Modify Folder Structure and Allow User Configurable 'Move When Finished' Dir

### ISSUE THREAD

**Issue by camjac251** [dangeroustech/StreamDL#80]
I was trying this out today to hopefully switch to from another project I've been using https://github.com/jrudess/streamdvr

The two have a different structure it seems. With streamdvr, it seems a little heavier I think, it can lag when you have 20 streamers monitored like I do. It mainly lags in starting and stopping the main process. That's one of the main reasons I'm hoping to move away from single threaded node to multithreaded python.

I noticed that when I  Ctrl C out of streamdl (KeyboardInterrupt), the app doesn't gracefully close or finish the post processing of the `.part` files. Could this be possible?

StreamDVR records streams to `streamdvr/capturing` then when you either gracefully exit the process or when it is finished, it will take the .ts file and remux it with fixing the aac stream, then sending it to the `streamdvr/captured` folder. https://github.com/jrudess/streamdvr/blob/master/scripts/postprocess_ffmpeg.sh

Although there is a downside to that for large streams. It can take a while, even an hour, to remux the file on a slower disk.

Would it be possible to support a similar folder structure to streamdvr?
It sorts stuff like this `streamdvr/captured/TWITCH/username/username_twitch_20200515_211526.mp4`

**Comment by biodrone** [comment]
I know that the .part files are an issue in the docker container because you can't both parse the commandline arguments and have the process run as PID 0 which is necessary for docker to close the container and pass the kill signal to the Python main thread. Are you using docker or running it on bare metal? 

I should be able to adopt a similar structure, I'll add a folder name tag to the YAML config once I'm done with the current logging improvements. don't know what the benefit of having the /captured folder in there is though? With streamdl you can set a root path with -o so you could set the root to streamdl/captured/ and then everything else would work from there? Or am I misunderstanding something?

**Comment by camjac251** [comment]
I'm running it on bare metal as is with poetry. I also did notice that streamers who went live after the script was started never started to record weirdly enough

**Comment by camjac251** [comment]
The benefit of having a capturing and captured folder for me is being able to make sure that I can modify the captured folder and not worry about something breaking. Mainly I use it for moving the files to cloud storage. So my captured folder is usually empty when everything is moved.

**Comment by biodrone** [comment]
Hmm, I run the docker version and I've never noticed issues like that, all my streams work fine even if I leave it for days at a time. If you notice that again can you submit a bug report and record the detail in the template? I'd be curious to see why that's happening...

**Comment by biodrone** [comment]
Ahh OK so it makes a distinction between downloading and captured, that was the bit of logic that was missing. I'm sure I can find a way to move them once they're finished, sure.

**Comment by biodrone** [comment]
@camjac251 Can you pull staging and see if that sorts out the moving and folder naming you were after? The `-o` option is now the transient downloading folder, `-m` is the folder to move to once finished.
